### ISSUE TITLE
startTun issue when a drone is active

### ISSUE THREAD

**Issue by matthieudesprez** [thunderk/spacetac#1]
Sometimes, the drone animation occurs then the next ship's turn gets skipped.

![capture d ecran 2017-06-08 a 23 13 12](https://user-images.githubusercontent.com/13304634/26951474-87e1f308-4ca1-11e7-8f8d-9d235d4421b3.png)

**Comment by thunderk** [comment]
The code that transferred game control to the player (or the AI) was confused by drone events happening right after a "ship change" event. It made this code assume that the wrong ship was in play.

This code was completely rewritten, fixing other timing issues as well.

Should be fixed in 07d0eb7a9d702d550fd0af9464fb727de2c48132

Thanks for the report !
